export const translations = {
  fr: {
    app:"MY Investissements", secure:"Accès sécurisé", login:"Connexion", register:"Inscription", email:"Adresse e-mail", password:"Mot de passe", name:"Nom complet", signin:"Se connecter", signup:"Créer mon compte", logout:"Déconnexion",
    heroTitle:"Gérez vos investissements, votre portefeuille et vos opérations depuis un seul espace.", heroText:"Les dépôts, retraits, investissements et échanges sont enregistrés dans Firebase. Les mouvements financiers sont validés par le service d’administration.",
    dashboard:"Tableau de bord", wallet:"Portefeuille", levels:"Niveaux", history:"Historique", deposit:"Dépôt", deposits:"Dépôts", withdraw:"Retrait", withdrawals:"Retraits", exchange:"Échange", exchanges:"Échanges", invest:"Investir", investments:"Investissements", amount:"Montant", currency:"Devise", method:"Méthode", reference:"Référence", status:"Statut", pending:"En attente", approved:"Approuvé", rejected:"Rejeté", paid:"Payé", submit:"Soumettre", balance:"Solde", invested:"Capital investi", profit:"Rendement estimé", admin:"Administration", investors:"Investisseurs", transactions:"Transactions", settings:"Paramètres", save:"Enregistrer", add:"Ajouter", rate:"Taux", period:"Période", weekly:"Hebdomadaire", annual:"Annuel", proof:"Lien de preuve", destination:"Compte/N° destination", from:"De", to:"Vers", welcome:"Bienvenue", manual:"Traitement manuel par le service d’administration", active:"Actif", inactive:"Inactif", choose:"Choisir", noData:"Aucune donnée", loading:"Chargement...", cancel:"Annuler", action:"Action", type:"Type", date:"Date", send:"Envoyer", communication:"Communication", messages:"Messages", virtualAssistant:"Assistant virtuel",
    adminUnique:"Admin unique", adminControl:"Contrôle des investisseurs, niveaux et opérations financières.", adminAuthorized:"Admin autorisé", activeLevels:"Niveaux actifs", pendingRequests:"Demandes en attente", activeInvestments:"Investissements actifs", flowByCurrency:"Flux par devise", recentActivity:"Activité récente", manageLevels:"Gestion des niveaux", adminDefinesLevel:"L’administrateur définit le montant, la devise, le taux et la période.", levelName:"Nom du niveau", levelPlaceholder:"Niveau 1", investorList:"Liste des investisseurs", requests:"Demandes", validateOperations:"Validation des opérations", all:"Toutes", noRequests:"Aucune demande.", manualOperations:"Opérations manuelles", adminDepositWithdrawal:"Dépôt / Retrait administrateur", manualWarning:"Enregistrez uniquement une opération que vous avez réellement vérifiée ou exécutée hors de l’application.", investor:"Investisseur", validateOperation:"Valider l’opération", privateMessaging:"Messagerie privée", selectInvestorMessage:"Choisissez un investisseur pour lire et envoyer des messages.", selectInvestor:"Sélectionnez un investisseur.", writeMessage:"Écrivez un message...", noInvestor:"Aucun investisseur", bankTransfer:"Virement bancaire", cash:"Espèces", openMessaging:"Ouvrir la messagerie", close:"Fermer", opened:"Ouverte", closed:"Fermée",
    mySpace:"Mon espace", investorOverview:"Suivez vos soldes, investissements et opérations validées.", myBalances:"Mes soldes", withdrawInfo:"Le service d’administration effectue le paiement puis confirme la référence.", exchangeInfo:"La conversion est exécutée après validation du taux par le service d’administration.", investmentLevels:"Niveaux d’investissement", levelsInfo:"Les montants et taux affichés sont configurés par le service d’administration. Les rendements sont des estimations et non une garantie.", myOperations:"Mes opérations", privateService:"Service MY", privateChatTitle:"Messagerie privée", privateChatInfo:"Cet espace apparaît uniquement lorsque le Service MY ouvre une conversation avec vous. Aucune identité personnelle de l’administrateur n’est affichée.", replyService:"Répondre au Service MY...", virtualAssistantText:"Posez une question sur votre compte, les dépôts, retraits, niveaux ou échanges.", assistantGreeting:"Bonjour 👋 Je peux vous expliquer le fonctionnement de MY Investissements. Je ne peux pas garantir un rendement ni effectuer un transfert d’argent à votre place.", assistantPlaceholder:"Ex. Comment faire un dépôt ?"
  },
  ht: {
    app:"MY Investissements", secure:"Aksè sekirize", login:"Koneksyon", register:"Enskripsyon", email:"Imèl", password:"Modpas", name:"Non konplè", signin:"Konekte", signup:"Kreye kont mwen", logout:"Dekonekte",
    heroTitle:"Jere envestisman, pòtfèy ak operasyon ou yo nan yon sèl espas.", heroText:"Depo, retrè, envestisman ak echanj yo anrejistre nan Firebase. Sèvis administrasyon an valide mouvman finansye yo.",
    dashboard:"Tablo de bò", wallet:"Pòtfèy", levels:"Nivo", history:"Istorik", deposit:"Depo", deposits:"Depo", withdraw:"Retrè", withdrawals:"Retrè", exchange:"Echanj", exchanges:"Echanj", invest:"Envesti", investments:"Envestisman", amount:"Montan", currency:"Deviz", method:"Metòd", reference:"Referans", status:"Estati", pending:"An atant", approved:"Apwouve", rejected:"Rejte", paid:"Peye", submit:"Soumèt", balance:"Balans", invested:"Kapital envesti", profit:"Retou estime", admin:"Administrasyon", investors:"Envestisè", transactions:"Tranzaksyon", settings:"Paramèt", save:"Anrejistre", add:"Ajoute", rate:"To", period:"Peryòd", weekly:"Pa semèn", annual:"Pa ane", proof:"Lyen prèv", destination:"Kont/N° destinasyon", from:"Soti nan", to:"Pou", welcome:"Byenvini", manual:"Sèvis administrasyon an trete operasyon an manyèlman", active:"Aktif", inactive:"Pa aktif", choose:"Chwazi", noData:"Pa gen done", loading:"Ap chaje...", cancel:"Anile", action:"Aksyon", type:"Kalite", date:"Dat", send:"Voye", communication:"Kominikasyon", messages:"Mesaj", virtualAssistant:"Asistan vityèl",
    adminUnique:"Admin inik", adminControl:"Kontwòl envestisè, nivo ak operasyon finansye.", adminAuthorized:"Admin otorize", activeLevels:"Nivo aktif", pendingRequests:"Demann an atant", activeInvestments:"Envestisman aktif", flowByCurrency:"Mouvman pa deviz", recentActivity:"Aktivite resan", manageLevels:"Jesyon nivo", adminDefinesLevel:"Admin lan defini montan, deviz, to ak peryòd la.", levelName:"Non nivo a", levelPlaceholder:"Nivo 1", investorList:"Lis envestisè yo", requests:"Demann", validateOperations:"Validasyon operasyon", all:"Tout", noRequests:"Pa gen demann.", manualOperations:"Operasyon manyèl", adminDepositWithdrawal:"Depo / Retrè admin", manualWarning:"Anrejistre sèlman yon operasyon ou verifye oswa egzekite reyèlman andeyò aplikasyon an.", investor:"Envestisè", validateOperation:"Valide operasyon an", privateMessaging:"Mesaj prive", selectInvestorMessage:"Chwazi yon envestisè pou li epi voye mesaj.", selectInvestor:"Chwazi yon envestisè.", writeMessage:"Ekri yon mesaj...", noInvestor:"Pa gen envestisè", bankTransfer:"Vireman bankè", cash:"Lajan kach", openMessaging:"Louvri mesajri a", close:"Fèmen", opened:"Louvri", closed:"Fèmen",
    mySpace:"Espas mwen", investorOverview:"Swiv balans, envestisman ak operasyon valide ou yo.", myBalances:"Balans mwen yo", withdrawInfo:"Sèvis administrasyon an fè peman an epi konfime referans lan.", exchangeInfo:"Konvèsyon an fèt apre sèvis administrasyon an valide to a.", investmentLevels:"Nivo envestisman", levelsInfo:"Se sèvis administrasyon an ki fikse montan ak to yo. Retou yo se estimasyon, yo pa garanti.", myOperations:"Operasyon mwen yo", privateService:"Sèvis MY", privateChatTitle:"Mesaj prive", privateChatInfo:"Espas sa a parèt sèlman lè Sèvis MY ouvri yon konvèsasyon avèk ou. Okenn idantite pèsonèl admin lan pa parèt.", replyService:"Reponn Sèvis MY...", virtualAssistantText:"Poze yon kesyon sou kont ou, depo, retrè, nivo oswa echanj.", assistantGreeting:"Bonjou 👋 Mwen ka eksplike kijan MY Investissements fonksyone. Mwen pa ka garanti yon retou ni fè transfè lajan pou ou.", assistantPlaceholder:"Eg. Kijan pou mwen fè yon depo?"
  },
  en: {
    app:"MY Investments", secure:"Secure access", login:"Login", register:"Sign up", email:"Email address", password:"Password", name:"Full name", signin:"Sign in", signup:"Create account", logout:"Logout",
    heroTitle:"Manage your investments, wallet and transactions from one place.", heroText:"Deposits, withdrawals, investments and exchanges are recorded in Firebase. Financial movements are validated by the administration service.",
    dashboard:"Dashboard", wallet:"Wallet", levels:"Levels", history:"History", deposit:"Deposit", deposits:"Deposits", withdraw:"Withdrawal", withdrawals:"Withdrawals", exchange:"Exchange", exchanges:"Exchanges", invest:"Invest", investments:"Investments", amount:"Amount", currency:"Currency", method:"Method", reference:"Reference", status:"Status", pending:"Pending", approved:"Approved", rejected:"Rejected", paid:"Paid", submit:"Submit", balance:"Balance", invested:"Invested capital", profit:"Estimated return", admin:"Administration", investors:"Investors", transactions:"Transactions", settings:"Settings", save:"Save", add:"Add", rate:"Rate", period:"Period", weekly:"Weekly", annual:"Annual", proof:"Proof link", destination:"Destination account/No.", from:"From", to:"To", welcome:"Welcome", manual:"Manually processed by the administration service", active:"Active", inactive:"Inactive", choose:"Choose", noData:"No data", loading:"Loading...", cancel:"Cancel", action:"Action", type:"Type", date:"Date", send:"Send", communication:"Communication", messages:"Messages", virtualAssistant:"Virtual assistant",
    adminUnique:"Unique admin", adminControl:"Control investors, levels and financial operations.", adminAuthorized:"Authorized admin", activeLevels:"Active levels", pendingRequests:"Pending requests", activeInvestments:"Active investments", flowByCurrency:"Flow by currency", recentActivity:"Recent activity", manageLevels:"Level management", adminDefinesLevel:"The administrator defines the amount, currency, rate and period.", levelName:"Level name", levelPlaceholder:"Level 1", investorList:"Investor list", requests:"Requests", validateOperations:"Operation validation", all:"All", noRequests:"No requests.", manualOperations:"Manual operations", adminDepositWithdrawal:"Admin deposit / withdrawal", manualWarning:"Record only an operation you have actually verified or executed outside the application.", investor:"Investor", validateOperation:"Validate operation", privateMessaging:"Private messaging", selectInvestorMessage:"Choose an investor to read and send messages.", selectInvestor:"Select an investor.", writeMessage:"Write a message...", noInvestor:"No investor", bankTransfer:"Bank transfer", cash:"Cash", openMessaging:"Open messaging", close:"Close", opened:"Open", closed:"Closed",
    mySpace:"My space", investorOverview:"Track your balances, investments and validated operations.", myBalances:"My balances", withdrawInfo:"The administration service makes the payment and then confirms the reference.", exchangeInfo:"The conversion is executed after the administration service validates the rate.", investmentLevels:"Investment levels", levelsInfo:"Amounts and rates are configured by the administration service. Returns are estimates and are not guaranteed.", myOperations:"My operations", privateService:"MY Service", privateChatTitle:"Private messaging", privateChatInfo:"This area appears only when MY Service opens a conversation with you. No personal administrator identity is displayed.", replyService:"Reply to MY Service...", virtualAssistantText:"Ask a question about your account, deposits, withdrawals, levels or exchanges.", assistantGreeting:"Hello 👋 I can explain how MY Investments works. I cannot guarantee a return or transfer money on your behalf.", assistantPlaceholder:"Example: How do I make a deposit?"
  },
  es: {
    app:"MY Inversiones", secure:"Acceso seguro", login:"Iniciar sesión", register:"Registrarse", email:"Correo electrónico", password:"Contraseña", name:"Nombre completo", signin:"Entrar", signup:"Crear mi cuenta", logout:"Cerrar sesión",
    heroTitle:"Gestione sus inversiones, cartera y operaciones desde un solo espacio.", heroText:"Los depósitos, retiros, inversiones y cambios se registran en Firebase. Los movimientos financieros son validados por el servicio de administración.",
    dashboard:"Panel", wallet:"Cartera", levels:"Niveles", history:"Historial", deposit:"Depósito", deposits:"Depósitos", withdraw:"Retiro", withdrawals:"Retiros", exchange:"Cambio", exchanges:"Cambios", invest:"Invertir", investments:"Inversiones", amount:"Monto", currency:"Moneda", method:"Método", reference:"Referencia", status:"Estado", pending:"Pendiente", approved:"Aprobado", rejected:"Rechazado", paid:"Pagado", submit:"Enviar", balance:"Saldo", invested:"Capital invertido", profit:"Rendimiento estimado", admin:"Administración", investors:"Inversores", transactions:"Transacciones", settings:"Configuración", save:"Guardar", add:"Agregar", rate:"Tasa", period:"Período", weekly:"Semanal", annual:"Anual", proof:"Enlace de comprobante", destination:"Cuenta/N° destino", from:"De", to:"A", welcome:"Bienvenido", manual:"Procesado manualmente por el servicio de administración", active:"Activo", inactive:"Inactivo", choose:"Elegir", noData:"Sin datos", loading:"Cargando...", cancel:"Cancelar", action:"Acción", type:"Tipo", date:"Fecha", send:"Enviar", communication:"Comunicación", messages:"Mensajes", virtualAssistant:"Asistente virtual",
    adminUnique:"Administrador único", adminControl:"Control de inversores, niveles y operaciones financieras.", adminAuthorized:"Administrador autorizado", activeLevels:"Niveles activos", pendingRequests:"Solicitudes pendientes", activeInvestments:"Inversiones activas", flowByCurrency:"Flujo por moneda", recentActivity:"Actividad reciente", manageLevels:"Gestión de niveles", adminDefinesLevel:"El administrador define el monto, la moneda, la tasa y el período.", levelName:"Nombre del nivel", levelPlaceholder:"Nivel 1", investorList:"Lista de inversores", requests:"Solicitudes", validateOperations:"Validación de operaciones", all:"Todas", noRequests:"No hay solicitudes.", manualOperations:"Operaciones manuales", adminDepositWithdrawal:"Depósito / Retiro del administrador", manualWarning:"Registre únicamente una operación que haya verificado o ejecutado realmente fuera de la aplicación.", investor:"Inversor", validateOperation:"Validar la operación", privateMessaging:"Mensajería privada", selectInvestorMessage:"Seleccione un inversor para leer y enviar mensajes.", selectInvestor:"Seleccione un inversor.", writeMessage:"Escriba un mensaje...", noInvestor:"Ningún inversor", bankTransfer:"Transferencia bancaria", cash:"Efectivo", openMessaging:"Abrir mensajería", close:"Cerrar", opened:"Abierta", closed:"Cerrada",
    mySpace:"Mi espacio", investorOverview:"Consulte sus saldos, inversiones y operaciones validadas.", myBalances:"Mis saldos", withdrawInfo:"El servicio de administración realiza el pago y luego confirma la referencia.", exchangeInfo:"La conversión se ejecuta después de que el servicio de administración valida la tasa.", investmentLevels:"Niveles de inversión", levelsInfo:"Los montos y las tasas son configurados por el servicio de administración. Los rendimientos son estimaciones y no están garantizados.", myOperations:"Mis operaciones", privateService:"Servicio MY", privateChatTitle:"Mensajería privada", privateChatInfo:"Este espacio aparece únicamente cuando el Servicio MY abre una conversación con usted. No se muestra ninguna identidad personal del administrador.", replyService:"Responder al Servicio MY...", virtualAssistantText:"Haga una pregunta sobre su cuenta, depósitos, retiros, niveles o cambios.", assistantGreeting:"Hola 👋 Puedo explicarle cómo funciona MY Inversiones. No puedo garantizar un rendimiento ni transferir dinero en su nombre.", assistantPlaceholder:"Ej. ¿Cómo hago un depósito?"
  }
};

export function getLang(){
  const lang=localStorage.getItem('my_lang')||'fr';
  return translations[lang]?lang:'fr';
}
export function setLang(lang){
  if(!translations[lang])lang='fr';
  localStorage.setItem('my_lang',lang);
  applyLang(lang);
  window.dispatchEvent(new CustomEvent('my-language-changed',{detail:{lang}}));
}
export function t(key,lang=getLang()){return translations[lang]?.[key]||translations.fr[key]||key;}

export function applyLang(lang=getLang()){
  document.documentElement.lang=lang;
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const key=el.dataset.i18n;
    if(translations[lang]?.[key]!==undefined)el.textContent=translations[lang][key];
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{
    const key=el.dataset.i18nPlaceholder;
    if(translations[lang]?.[key]!==undefined)el.placeholder=translations[lang][key];
  });
  document.querySelectorAll('[data-i18n-title]').forEach(el=>{
    const key=el.dataset.i18nTitle;
    if(translations[lang]?.[key]!==undefined)el.title=translations[lang][key];
  });
  const select=document.querySelector('#langSelect');
  if(select)select.value=lang;
}

export function bindLanguageSelector(){
  const select=document.querySelector('#langSelect');
  if(select&&!select.dataset.i18nBound){
    select.dataset.i18nBound='1';
    select.addEventListener('change',e=>setLang(e.target.value));
  }
  applyLang();
}
