export const translations = {
  fr:{app:"MY Investissements",login:"Connexion",register:"Inscription",email:"Adresse e-mail",password:"Mot de passe",name:"Nom complet",signin:"Se connecter",signup:"Créer mon compte",logout:"Déconnexion",dashboard:"Tableau de bord",wallet:"Portefeuille",levels:"Niveaux",history:"Historique",deposit:"Dépôt",withdraw:"Retrait",exchange:"Échange",invest:"Investir",amount:"Montant",currency:"Devise",method:"Méthode",reference:"Référence",status:"Statut",pending:"En attente",approved:"Approuvé",rejected:"Rejeté",submit:"Soumettre",balance:"Solde",invested:"Capital investi",profit:"Rendement estimé",admin:"Administration",investors:"Investisseurs",transactions:"Transactions",settings:"Paramètres",save:"Enregistrer",add:"Ajouter",rate:"Taux",period:"Période",weekly:"Hebdomadaire",annual:"Annuel",proof:"Lien de preuve",destination:"Compte/N° destination",from:"De",to:"Vers",welcome:"Bienvenue",secure:"Accès sécurisé",manual:"Traitement manuel par l’administrateur",active:"Actif",inactive:"Inactif",choose:"Choisir",noData:"Aucune donnée"},
  ht:{app:"MY Investissements",login:"Konekte",register:"Enskri",email:"Imèl",password:"Modpas",name:"Non konplè",signin:"Konekte",signup:"Kreye kont mwen",logout:"Dekonekte",dashboard:"Tablo de bò",wallet:"Pòtfeuy",levels:"Nivo",history:"Istorik",deposit:"Depo",withdraw:"Retrè",exchange:"Echanj",invest:"Envesti",amount:"Montan",currency:"Deviz",method:"Metòd",reference:"Referans",status:"Estati",pending:"An atant",approved:"Apwouve",rejected:"Rejte",submit:"Soumèt",balance:"Balans",invested:"Kapital envesti",profit:"Retou estime",admin:"Administrasyon",investors:"Envestisè",transactions:"Tranzaksyon",settings:"Paramèt",save:"Anrejistre",add:"Ajoute",rate:"To",period:"Peryòd",weekly:"Pa semèn",annual:"Pa ane",proof:"Lyen prèv",destination:"Kont/N° destinasyon",from:"Soti",to:"Pou",welcome:"Byenvini",secure:"Aksè sekirize",manual:"Admin trete operasyon yo manyèlman",active:"Aktif",inactive:"Pa aktif",choose:"Chwazi",noData:"Pa gen done"},
  en:{app:"MY Investments",login:"Login",register:"Sign up",email:"Email address",password:"Password",name:"Full name",signin:"Sign in",signup:"Create account",logout:"Logout",dashboard:"Dashboard",wallet:"Wallet",levels:"Levels",history:"History",deposit:"Deposit",withdraw:"Withdrawal",exchange:"Exchange",invest:"Invest",amount:"Amount",currency:"Currency",method:"Method",reference:"Reference",status:"Status",pending:"Pending",approved:"Approved",rejected:"Rejected",submit:"Submit",balance:"Balance",invested:"Invested capital",profit:"Estimated return",admin:"Administration",investors:"Investors",transactions:"Transactions",settings:"Settings",save:"Save",add:"Add",rate:"Rate",period:"Period",weekly:"Weekly",annual:"Annual",proof:"Proof link",destination:"Destination account/No.",from:"From",to:"To",welcome:"Welcome",secure:"Secure access",manual:"Manually processed by the administrator",active:"Active",inactive:"Inactive",choose:"Choose",noData:"No data"},
  es:{app:"MY Inversiones",login:"Iniciar sesión",register:"Registrarse",email:"Correo electrónico",password:"Contraseña",name:"Nombre completo",signin:"Entrar",signup:"Crear mi cuenta",logout:"Cerrar sesión",dashboard:"Panel",wallet:"Cartera",levels:"Niveles",history:"Historial",deposit:"Depósito",withdraw:"Retiro",exchange:"Cambio",invest:"Invertir",amount:"Monto",currency:"Moneda",method:"Método",reference:"Referencia",status:"Estado",pending:"Pendiente",approved:"Aprobado",rejected:"Rechazado",submit:"Enviar",balance:"Saldo",invested:"Capital invertido",profit:"Rendimiento estimado",admin:"Administración",investors:"Inversores",transactions:"Transacciones",settings:"Configuración",save:"Guardar",add:"Agregar",rate:"Tasa",period:"Período",weekly:"Semanal",annual:"Anual",proof:"Enlace de comprobante",destination:"Cuenta/N° destino",from:"De",to:"A",welcome:"Bienvenido",secure:"Acceso seguro",manual:"Procesado manualmente por el administrador",active:"Activo",inactive:"Inactivo",choose:"Elegir",noData:"Sin datos"}
};

export function getLang(){return localStorage.getItem('my_lang')||'fr';}
export function setLang(lang){localStorage.setItem('my_lang',lang);applyLang(lang);}
export function t(key,lang=getLang()){return translations[lang]?.[key]||translations.fr[key]||key;}
export function applyLang(lang=getLang()){
  document.documentElement.lang=lang;
  document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(translations[lang]?.[key])el.textContent=translations[lang][key];});
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const key=el.dataset.i18nPlaceholder;if(translations[lang]?.[key])el.placeholder=translations[lang][key];});
  const select=document.querySelector('#langSelect'); if(select)select.value=lang;
}
export function bindLanguageSelector(){const select=document.querySelector('#langSelect');if(select)select.addEventListener('change',e=>setLang(e.target.value));applyLang();}
